### ISSUE TITLE
汇率会不会成为房地产风向标？

### ISSUE THREAD

**Issue by talker93** [shenzhengfang/kkndme_tianya#46]
作者在十年前做这些分析还是比较准确的。包括对封建时代历史事件的一些总结。
不过好像对国际市场讨论得比较少。

财富越集中，财富利用率越低，用工成本越来越高，生产力不增反降。
这样下去出口还会好吗？外汇还能结余多少？

虽然房价可以维稳，但是汇率靠什么维稳？

到了排队买大米的时候，风暴就不远了。
这种事不需要等几百年一遇的小冰期，31年前就出现过一次。

**Comment by MachiBarton** [comment]
汇率问题也不大啊现在，没啥担心的。
